import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import codeImport from 'remark-code-import';

const UPSTREAM_REPO = 'https://github.com/zcash/halo2';
const FORK_REPO = 'https://github.com/dannywillems/halo2';
const PINNED_REF = '32a87582dfb0ad9364ef3ffe71751ceab2a502ea';

const config: Config = {
  title: 'halo2 Onboarding',
  tagline:
    'A code-anchored, contribution-oriented course for the zcash/halo2 PLONKish proving system.',
  favicon: 'img/favicon.ico',

  url: 'https://dannywillems.github.io',
  baseUrl: '/halo2/',

  organizationName: 'dannywillems',
  projectName: 'halo2',

  onBrokenLinks: 'throw',

  trailingSlash: false,

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          remarkPlugins: [
            remarkMath,
            // remark-code-import inflates ```lang file=path#L1-L5
            // fences with the cited line range from disk at build
            // time. Paths are relative to the Markdown file.
            [codeImport, { rootDir: __dirname, allowImportingFromOutside: true }],
          ],
          rehypePlugins: [rehypeKatex],
          editUrl: `${FORK_REPO}/edit/onboarding/onboarding/`,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  stylesheets: [
    {
      href: 'https://cdn.jsdelivr.net/npm/katex@0.17.0/dist/katex.min.css',
      type: 'text/css',
      integrity:
        'sha384-vlBdW0r3AcZO/HboRPznQNowvexd3fY8qHOWkBi5q7KGgqJ+F48+DceybYmrVbmB',
      crossorigin: 'anonymous',
    },
  ],

  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexBlog: false,
        indexDocs: true,
        indexPages: true,
        language: ['en'],
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  themeConfig: {
    image: 'img/halo2-social-card.png',
    announcementBar: {
      id: 'ai-generated-disclaimer',
      content:
        'This site is auto-generated by Claude Code and may contain errors. The halo2 source code is authoritative; always cross-check against the repository before acting on anything here.',
      backgroundColor: '#fef3c7',
      textColor: '#78350f',
      isCloseable: false,
    },
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'halo2 Onboarding',
      logo: {
        alt: 'halo2',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Course',
        },
        {
          href: UPSTREAM_REPO,
          label: 'Upstream',
          position: 'right',
        },
        {
          href: `${FORK_REPO}/tree/onboarding`,
          label: 'Course source',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Repository',
          items: [
            { label: 'Upstream zcash/halo2', href: UPSTREAM_REPO },
            {
              label: 'Pinned commit',
              href: `${UPSTREAM_REPO}/commit/${PINNED_REF}`,
            },
            {
              label: 'Course source (fork)',
              href: `${FORK_REPO}/tree/onboarding`,
            },
          ],
        },
        {
          title: 'Specifications',
          items: [
            {
              label: 'Halo paper (eprint 2019/1021)',
              href: 'https://eprint.iacr.org/2019/1021',
            },
            {
              label: 'PLONK paper (eprint 2019/953)',
              href: 'https://eprint.iacr.org/2019/953',
            },
            {
              label: 'The Halo 2 Book',
              href: 'https://zcash.github.io/halo2/',
            },
          ],
        },
      ],
      copyright:
        'Course content licensed MIT/Apache 2.0. halo2 is (c) Electric Coin Company and contributors.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'bash', 'toml', 'json', 'yaml', 'diff'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
